apiVersion: 1

datasources:
  - name: FactoryMind-InfluxDB
    type: influxdb
    access: proxy
    uid: fm-influxdb
    url: http://factorymind-influxdb:8086
    isDefault: true
    editable: false
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET}
      tlsSkipVerify: false
      timeInterval: "1s"
      httpMode: POST
    secureJsonData:
      token: ${INFLUX_TOKEN}
