apiVersion: 1

datasources:
  - name: FactoryMind-PostgreSQL
    type: postgres
    access: proxy
    uid: fm-postgres
    url: factorymind-postgres:5432
    user: ${POSTGRES_USER}
    database: ${POSTGRES_DB}
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
      maxOpenConns: 25
      maxIdleConns: 25
      connMaxLifetime: 14400
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
